### ISSUE TITLE
feedproviders example in README seems outdated

### ISSUE THREAD

**Issue by hbruch** [entur/lamassu#152]
The current feedproviders.yml example in README.md seems to be outdated.

It should read:

```
        lamassu:
            providers:
              - systemId: mysystem
                operatorId: MFM:Operator:myoperator
                operatorName: My operator
                codespace: MFM
                url: https://myfavoritegbfsfeeed.com/gbfs.json
                language: en
 ```
