### ISSUE TITLE
Configuring custom pricing plans should be documented

### ISSUE THREAD

**Issue by hbruch** [entur/lamassu#258]
Lamassu supports the cofiguration of custom pricing plans.

How to do this (an example is [provided in this PR](https://github.com/entur/lamassu/pull/257#issuecomment-1717442025)), and when this would be useful, should be documented.

I.e. it is unclear to me, if it is used to overwrite/redefine existing pricing information, e.g. because they are outdated, should be better described etc., or if it is also possible to augment feeds which don't provide pricing plans at all. In this case: are vehicle_types augmented by default pricing plans (which one then) or should the be redefined in the config also? Do these defined vehicle types overwrite the original vehicle_types info or are they merged in some way?

**Comment by testower** [comment]
I added support for providing vehicle types and pricing plans via the configuration as an escape hatch to deal with low quality data feeds at the early beginning of this project. I actually never intended for it to be a permanent feature, so perhaps hence the lack of clarity / documentation on it. I agree that if we intend to keep it, it should be documented properly.

As you'll see in the feed mappers:

https://github.com/entur/lamassu/blob/master/src/main/java/org/entur/lamassu/mapper/feedmapper/VehicleTypesFeedMapper.java#L44

and

https://github.com/entur/lamassu/blob/master/src/main/java/org/entur/lamassu/mapper/feedmapper/SystemPricingPlansFeedMapper.java#L47

if these are provided in the configuration for that system, any existing feed data will be completely replaced, both in the gbfs endpoints and in the aggregated graphql api. So there is no attempt to merge with existing data.

> In this case: are vehicle_types augmented by default pricing plans (which one then) or should the be redefined in the config also?

Not automatically, no. But you can of course define it yourself. So to use your own example (trimmed down a bit): 

```
lamassu:
  providers:
    - systemId: lime_zu
      operatorId: LME:Operator:lime
      operatorName: Lime
      codespace: DKY
      url: "https://data.lime.bike/api/partners/v2/gbfs/zug/gbfs.json"
      language: en
      vehicleTypes:
        - vehicleTypeId: TestVehicleType
           defaultPricingPlanId: TestPlan
           ....
      pricingPlans:
        - planId: TestPlan
          name: TestPlan
          ...
```
