### ISSUE TITLE
Inconsistent case handling for non lowercase system_ids

### ISSUE THREAD

**Issue by hbruch** [entur/lamassu#427]
## Expected behavior
Either lamassu should enforce lowercase system_ids in feedproviders.yml, or it should not lowercase the system_id when publishing feed urls.

## Observed behavior
We configured a provider using it's original mixed case system_id (e.g. provider_TOWN).

Lamassu publishes this feed in http://lamassu:8080/gbfs as http://lamassu:8080/gbfs/provider_town/gbfs, which results in a 404 error when requested. http://lamassu:8080/gbfs/provider_TOWN/gbfs works.

## Version of lamassu used (exact commit hash or JAR name)
https://github.com/entur/lamassu/commit/8cff0c895aa590d7b113b41c79a2d57972c5a3ec

## Data sets in use (links to GBFS feeds)
any

## Steps to reproduce the problem
Configure e.g.
```
lamassu:
  providers:
    - systemId: provider_TOWN
      operatorId: op:Operator:p
      operatorName: Provider
      codespace: op
      url: "https://provider.com/gbfs.json"
      language: en
```
http://localhost:8080/gbfs will respond with:
```json
{"systems":[{"id":"provider_TOWN","url":"http://localhost:8080/gbfs/provider_town/gbfs"}
```
