### ISSUE TITLE
Some feeds are reported as app_lamassu_gbfs_validation_missingrequiredfile though feed exists

### ISSUE THREAD

**Issue by hbruch** [entur/lamassu#430]
## Expected behavior
For valid feeds, like e.g. this [donkey feed](https://gbfs-validator.netlify.app/validator?url=https://stables.donkey.bike/api/public/gbfs/2/donkey_ge/gbfs.json), lamassu should not report app_lamassu_gbfs_validation_missingrequiredfile.

## Observed behavior
With current Lamassu commit 0ddee08,  starting from 02a755a (merge of consume-v3), we receive 

```
app_lamassu_gbfs_validation_missingrequiredfile{file="gbfs",system="donkey_ge",version="2.3",} 1.0
```

## Version of lamassu used (exact commit hash or JAR name)
0ddee08

## Data sets in use (links to GBFS feeds)
https://stables.donkey.bike/api/public/gbfs/2/donkey_ge/gbfs.json

## Configuration used
```
lamassu:
  providers:
    - systemId: donkey_ge
      operatorId: DKY:Operator:donkey
      operatorName: Donkey Republic
      codespace: DKY
      url: "https://stables.donkey.bike/api/public/gbfs/2/donkey_ge/gbfs.json"
      language: de
```
