### ISSUE TITLE
RuntimeExceptions during subscription setup prevents retries

### ISSUE THREAD

**Issue by testower** [entur/lamassu#442]
Given a simple test case that causes a NPE while trying to extract feeds from the discovery file we expect that  the system will back off and try again later to setup the subscription, assuming that there is a temporary error in the upstream data.

What actually happens is that the exception propagates to the forkjoinpool, and is the subscription setup method never returns, thus is never given a chance to schedule a retry.

## Version of lamassu used (exact commit hash or JAR name)

271c0f74344ec2d1cd63d01a6bb1285a470758f1

## Data sets in use (links to GBFS feeds)

```json
{
  "last_updated": 1714131556,
  "ttl": 3600,
  "version": "2.3",
  "data": null
}
```

## Configuration used

```
lamassu:
  providers:
    - systemId: test
      operatorId: TST:Operator:Test
      operatorName: Test
      codespace: TST
      url: http://localhost:3001/gbfs.json
      language: "no"
```
