### ISSUE TITLE
Make pricing plans optionnal

### ISSUE THREAD

**Issue by enrikomic** [entur/lamassu#674]
**Is your feature request related to a problem?**
Stations and vehicles ignored when no pricing plan provided

**Goal / high level use-case**
system_pricing_plans.json is an optional file in GBFS reference. I would like to use Lamassu transformers and graphql API when pricing plans are not provided

**Describe the solution you'd like**
Remove pricing plan filter in EntityCacheUpdater

https://github.com/entur/lamassu/blob/cb24f4756331052ef620ca28788f936dba260355/src/main/java/org/entur/lamassu/leader/entityupdater/EntityCachesUpdater.java#L193-L194

And

https://github.com/entur/lamassu/blob/cb24f4756331052ef620ca28788f936dba260355/src/main/java/org/entur/lamassu/leader/entityupdater/EntityCachesUpdater.java#L215-L216

**Additional context**
My firsts tests removing both conditions seems to be OK. But could you confirm it's a good idea and there are no cascading effects?

**Comment by testower** [comment]
The reason we required pricing plans (and vehicle types) when we first designed this system was that we looked at what, beyond the minimum requirements of the spec, is the minimum data richness we desire in order to provide a reasonably useful aggregated dataset. In other words, what would a user expect need to know in order to assess different offers from different providers. We figured knowing what type of vehicle and the cost to rent it should be included in that minimum.

Now others may have other needs for their systems, but this was part of the foundation for us. The GraphQL API has these fields as non-optional - so changing this would break the api.

As a workaround, you *could* include static pricing plans (and vehicle types) as part of the feed provider configuration. This is an undocumented feature. We made it to compensate for lacking data in the early days. I would not particularly recommend using it, especially not with fake data, but now you know it's there. See https://github.com/entur/lamassu/blob/master/src/main/java/org/entur/lamassu/model/provider/FeedProvider.java#L38-L39

**Comment by enrikomic** [comment]
Thank you for your response, and for the tip!

That perfectly solves my issue. Here's what the added configuration block looks like:
```
pricingPlans:
        - planId: "Lib1"
          name: "Liberté 1 trajet"
          currency: "EUR"
          price: 1.0
          isTaxable: false
          description: "1€ permet de débloquer le vélo. Puis avec un vélo mécanique : profitez des 30 premières minutes gratuites. Au-delà, une tarification de 0,50€ par demi-heure supplémentaire est appliquée."
          perMinPrincing:
            - start: 30
              interval: 30
              rate: 0.5
          perKmPrincing:
            - start: 0
              interval: 0
              rate: 0
```
